version: '3.4'

services:
  clinicappointment:
    image: ${DOCKER_REGISTRY-}clinicappointment
    ports:
      - 3001:80 
    build:
      context: .
      dockerfile: ClinicAppointment\Dockerfile
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD= P@$$w0rd
      - POSTGRES_USER= postgres
      - POSTGRES_DB= AppointmentDb
    volumes:
      - ClinicAppointment:/data/db
volumes:
  ClinicAppointment:  