version: '3.4'

services:
  clinicappointment:
    image: ${DOCKER_REGISTRY-}clinicappointment
    ports:
      - 3002:3002 
    build:
      context: .
      dockerfile: ClinicAppointment\Dockerfile
  db:
    image: postgres
    ports:
      - 5431:5431
    restart: always
    environment:
      POSTGRES_PASSWORD: P@$$w0rd
    volumes:
      - ClinicAppointment:/data/db

volumes:
  ClinicAppointment:  